# Generated by Django 5.2.6 on 2025-09-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='administrador',
            new_name='administrador_id',
        ),
    ]
