# Generated by Django 5.2.6 on 2025-09-10 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardia', '0002_rename_administrador_comunicado_administrador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='administrador_id',
            field=models.ForeignKey(db_column='administrador_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
