# Generated by Django 5.2.6 on 2025-09-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('bloque', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('numero', models.CharField(max_length=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
    ]
