# Generated by Django 5.2.6 on 2025-09-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='tipo_unidad',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('deposito', 'Depósito'), ('parqueadero', 'Parqueadero'), ('otro', 'Otro')], default='apartamento', help_text='Tipo de unidad', max_length=20),
        ),
    ]
